apiVersion: v1
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm
kind: Secret
metadata:  
  name: nagp-devops-us-master-secret
  namespace: kubernetes-cluster-surabhirathore
  labels:
   app: nagp-devops-us-master
type: Opaque